id: "docker-worker"
name: "OLO Worker (docker)"
server:
  host: "0.0.0.0"
  port: 8080
workflowDefinitions:
  scanFolder: "/app/olo-configuration/current-active"
  recursive: true
temporal:
  namespace: "default"
  target: "temporal:7233"
cache:
  enabled: true
  host: "redis"
  port: 6379
input:
  maxLocalMessageSize: 50
metadata:
  environment: "docker"
  oloApiBaseUrl: "http://olo:7080"