package org.olo.annotation;

import java.util.List;

/**
 * Classpath locations for generated extension catalogs.
 */
public final class OloCatalogLocations {

    public static final String CATALOG_DIR = "META-INF/olo/catalog";

    public static final String NODES_CATALOG = CATALOG_DIR + "/nodes.json";
    public static final String TOOLS_CATALOG = CATALOG_DIR + "/tools.json";
    public static final String HOOKS_CATALOG = CATALOG_DIR + "/hooks.json";

    /**
     * Per-type catalogs merged by {@link org.olo.annotation.catalog.ExtensionCatalogLoader}.
     * {@link #MERGED_CATALOG} is intentionally excluded — it is a derived per-module snapshot only.
     */
    public static final List<String> AUTHORITATIVE_CATALOGS =
            List.of(NODES_CATALOG, TOOLS_CATALOG, HOOKS_CATALOG);
    /**
     * Per-module convenience bundle (all non-empty kinds). Generated by the annotation processor for
     * indexing, marketplace inspection, and CLIs — not merged by {@code ExtensionCatalogLoader}.
     */
    public static final String MERGED_CATALOG = CATALOG_DIR + "/catalog.json";

    private OloCatalogLocations() {
    }
}
